export class Dvaspirante {
    vasp_folioaspi: number;
    vasp_numconnvo:number;
    vasp_ures: string;
    vasp_descures: string;
    vasp_prog: string;
    vasp_descprog: string;
    vasp_descconv: string;
    vasp_nombre: string;
    vasp_paterno: string;
    vasp_materno: string;
    vasp_fnac: string;
    vasp_genero:Date;
    vasp_curp: string;
    vasp_correo: string;
    vasp_rfc:string;
    vasp_ecivil:string;
    vasp_nacionalidad: string;
    vasp_calle: string;
    vasp_numero: string;
    vasp_colonia: string;
    vasp_telcasa: string;
    vasp_telofi: string;
    vasp_telcel: string;
    vasp_escolaridad: number;
    vasp_descescolaridad: string;
    vasp_escprocede:string;
    vasp_titulo: string;
    vasp_concedula: string;
    vasp_trabaja: string;
    vasp_ltrabajo: string;
    vasp_actividad: string;
    vasp_puesto: string;
    vasp_antiguedad: string;
    vasp_edonac: string;
    vasp_descedonac: string;
    vasp_munnac: string;
    vasp_descmunnac: string;
    vasp_edoprocede: string;
    vasp_descedoproc: string;
    vasp_munprocede: string;
    vasp_descmunproc:string;
    vasp_matricula:string;
}